/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const CONFIG = {
  MAX_FILE_SIZE_MB: 50,
  MAX_ROWS_FULL_LOAD: 20000,
  SAMPLE_ROWS: 10000,
  RANDOM_SEED: 42,
  OUTLIER_Z_THRESHOLD: 3.0,
  MISSING_THRESHOLD: 0.7,
  CARDINALITY_RATIO_THRESHOLD: 0.5,
  CATEGORICAL_UNIQUE_LIMIT: 10,
  CLUSTERING_K_RANGE: [2, 6],
  ANOMALY_CONTAMINATION: 0.05,
  FORECAST_PERIODS: 5,
};
